### ISSUE TITLE
Functions and methods

### ISSUE THREAD

**Issue by ViktorBobrovsky** [Artinov/topic-request#3]
1. Please tell us with simple words what is a function and her parameters. When they use "return" and why it so important. 
2. Also please explain what the role have methods.
PS. As really beginner i often dont understand many things in JS that we learnt. May be we should learn from the basic points because i can repeat the code that you write on lessons and it works, but when i  trying to repeat it home as i uderstood - it doesnt))

**Comment by eko24ive** [comment]
@ViktorBobrovsky great idea.
I'll prepare some basic material and bring it up on upcoming lesson.

**Comment by eko24ive** [comment]
I did my best !
